### ISSUE TITLE
pluginapi-beta branch runs significantly worse.

### ISSUE THREAD

**Issue by DukeofLeet** [northwood-studios/NwPluginAPI#102]
After installong the pluginapi-beta branch to my server and running some tests runs with a small playtest group. The server itself stutters to an almost unplayable level even without any plugins loaded. The standard public-beta branch does not have this issue at all and has been running nominally even with a higher player count than our test matches.

Note that all stuttering and server-side lag stopped the moment I had down patched back to the public-beta.

**Comment by zabszk** [comment]
Performance of the base game isn't an issue directly related to the NW Plugin API. It should be reported using our bug reporting form (https://support.scpslgame.com/bug-report).
