### ISSUE TITLE
OnSpawn strangeness

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#104]
I use this to check if the player is the server:
![image](https://user-images.githubusercontent.com/18099825/209242459-12d90467-6f01-461f-8bfc-464d2687f3d0.png)

This fails because the server instance is null. How can this be when the player is the server instance and the player is not null?

**Comment by moddedmcplayer** [comment]
#61 you sure you on lastest ver?

**Comment by KarlOfDuty** [comment]
Yep
