### ISSUE TITLE
Missing important arguments in some events and other issues

### ISSUE THREAD

**Issue by Michal78900** [northwood-studios/NwPluginAPI#108]
- [x] **PlayerInteractElevator**
No Elevator argument.

- [x] **PlayerInteractShootingTarget**
No ShootingTarget argument.

- [x] **PlayerReceiveEffect**
No Intensity arguement. It is not necessary, however the Duration argument exists for some reason so I don't know why Intensity should not.

- [x] **PlayerInteractScp330**
Would be funny if you could bypass the taken candies check. Currently returning false will cause not taking any candies at all I think.

- [x] **PlayerRemoveHandcuffs**
I would also allow cuffing SCPs by removing `referenceHub.GetRoleId().GetTeam() != Team.SCPs` check.

- [x] **PlayerThrowItem**
I would add an argument for manipulating item's velocity and stuff, for example `Rigidbody` which is before in the same method.

- [x] **PlaceBlood** and **PlaceBulletHole**
No position argument or anything like that.

- [x] **GrenadeExploded**
No Attacker and Position arguments. `ExplosionGrenade` doesn't provide such stuff unless I'm blind.

- [x] **PlayerThrowProjectile**
Just give entire `ThrowableItem.ProjectileSettings` as an argument instead of creating 4 arguments from that struct.

- [x] **ItemSpawned**
There is only `ItemType` argument. What kind of item was created and where? What's it's door trigger name?

- [x] **RoundEnd**
Canceling this event will kill entire coroutine preventing round from ever being ended. You should also give properties from `Statistics.CurrentRound` or entire class reference if someone would like to change the stats for some reason.

- [x] **Scp914Activate** and **Scp914KnobChange**
No knob setting or previous knob setting arguments.

- [x] **Scp914UpgradePickup**
You can give an argument to what pickup was pickup upgraded. Also if you want position override.

- [x] **Scp914UpgradeInventory**
Same as above, what's the new item.

- [x] **PlayerInteractLocker**
You should give `LockerChamber` argument. ColliderId may be confusing.

**Comment by Michal78900** [comment]
I forgot to mention that you guys should rework the naming convetion of events
For example `PlayerDeath` event. From that name I would assume that the event takes place **after** player has died. But no, it takes place **before**. Renaming it `PlayerDying` would say, that the player is in process of dying but isn't dead yet, therefor the event can be canceled.

**Comment by x3rt** [comment]
- [ ]  TeamRespawn(ing/ed)
Should include a list of the players respawning
