### ISSUE TITLE
Player Rotation

### ISSUE THREAD

**Issue by warquys** [northwood-studios/NwPluginAPI#109]
Change 
```cs
 void OverridePosition(Vector3 position, Vector3 deltaRotation)
```
to 
```cs
void OverridePosition(Vector3 position, Vector3 rotation)
```
or add the possibility to change the rotation by delta or not, via a bool
like this :
```cs
void OverridePosition(Vector3 position, Vector3 rotation, bool delta)
```

And take care of the X axis (vertical).

**Comment by zabszk** [comment]
The base games uses delta rotation. I don't think that calculating a delta is a problem, because it's basically just subtracting two vectors.

**Comment by warquys** [comment]
but for the X axis?
