### ISSUE TITLE
GRPC Assembly

### ISSUE THREAD

**Issue by ElecTwix** [northwood-studios/NwPluginAPI#124]
### **What I was trying to do:**

I was building a gRPC client for a Plugin to get data from other gRPC Servers.

### What I Did

First I build a Console App on the same version of .NET framework and it was working fine.
then I build it I ported all codes and build the project and it was building perfectly fine.

firstly I didn't put `grpc_csharp_ext.x64.dll` to the dependencies I had have shared library ( so ) for that created link for that

### What Did I Use

 I'm using Nuget "Grpc.Core, Grpc.Core.Api, Grpc.Net.Client" for gRPC Connection. 

### What Happened

when this line is executed gives
```
var channel = new Channel("localhost:50080", credentials);
```

then after the error, I try to put `grpc_csharp_ext.x64.dll` into dependencies,
I get this `System.DllNotFoundException: grpc_csharp_ext`

### After I put dll into the dependencies

I tried to put dll into the dependencies and I got this when the server started.

```
 Error while loading an assembly at grpc_csharp_ext.x64.dll
```

**Comment by moddedmcplayer** [comment]
Does the nuget package support .net 4.8?

**Comment by ElecTwix** [comment]
yes, it is.
and also like I said in the issue I made .net framework 4.8, Console App it is working fine with gRPC and can get data from gRPC server, etc.

**Comment by moddedmcplayer** [comment]
Can you try making it a class library?

**Comment by ElecTwix** [comment]
Hi,
I made a Class library and build it and created new consoleapp and executed the command first it didn't work after I put `libgrpc_csharp_ext.x64.so` next to the binary now works perfectly well but the problem is I did the same in PluginAPI maybe I missed to the binary path if you think that's the case please let me know the path I could test it out.

**Comment by moddedmcplayer** [comment]
libgrpc_csharp_ext.x64.so is that a dll? Youre better off asking in the nwapi discord then here on github

**Comment by ElecTwix** [comment]
`libgrpc_csharp_ext.x64.so` is the shared library for Linux.
I asked in discord no one responded that way I created an issue in the first place.

**Comment by moddedmcplayer** [comment]
ask again and ping me

**Comment by ElecTwix** [comment]
After Long talks seem like NwPluginAPI doesn't support gRPC.
