### ISSUE TITLE
OnPickupDropped

### ISSUE THREAD

**Issue by REALMWTH** [northwood-studios/NwPluginAPI#125]
Called when item is ALREADY dropped
Returns ReferenceHub and ItemPickupBase

**Comment by SrLicht** [comment]
What do you want exactly, when a player picks up an item that was already dropped or after an item is effectively dropped?

**Comment by REALMWTH** [comment]
> What do you want exactly, when a player picks up an item that was already dropped or after an item is effectively dropped?

I want new event to be called when pickup is already instantiated and spawned, so I can manipulate it

**Comment by SrLicht** [comment]
But PlayerDropItem is exactly what you are looking for is a cancelable event when a player drops an item, you can set return false to cancel the event and destroy the item with ItemBase.DestroySelf();

**Comment by REALMWTH** [comment]
I want to manipulate ItemPickup's parameters after spawn, such as: ammo amount, attachments, localscale etc
