### ISSUE TITLE
Void / Random TP problem

### ISSUE THREAD

**Issue by sssssssthedev** [northwood-studios/NwPluginAPI#139]
I'm not sure if this is a problem with nwpluginapi itself or the assembly-csharp, but players sometimes spawn in the void or a scp spawns in entrance. I feel like this is a problem if the PlayerRoleChange event is used by a lot of plugins, but i'm not sure. 
![AlXanFoh](https://user-images.githubusercontent.com/69808781/210562337-ca326737-fb4e-4539-8805-519be14b4621.png)

**Comment by zabszk** [comment]
Hi,

It's either an issue with some plugin you use (try removing all the plugins, if it works try adding them one by one to determine which one is causing it) or with the base game itself (in that case issue occurs even without the plugins, in such case report it as a game bug: https://support.scpslgame.com/bug-report).
