### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by Jesus-QC** [northwood-studios/NwPluginAPI#14]
The project structure is very wrong, it is based on wrappers for the main classes.

The structure it should have is just implement the api into the main classes, this won't only provide a higher maintainability but readability and stability.

**Comment by PintTheDragon** [comment]
There are a few considerations that have to be taken for a non-wrapper API approach. The biggest one would be that it's very difficult to make it opensource without making the entire game opensource, which won't happen.

I definitely agree that while integrating it into the game assembly directly would reduce code duplication and make it easier to maintain, making the API opensource allows for greater control over the API for the people who will actually use it. It's a bit of a balance between community and maintainability, and the whole purpose of this project is for community.

The other big issue that I can see with integrating the API into the game is that the game's code is very prone to having breaking changes. It isn't officially meant to be used by anything, so there's no issues with changing how the code is internally structured. If it's actually meant to be used as an API, however, this notion comes toppling down and I can't imagine there being any decision Northwood could make that would fit the needs of their developers as well as their community at large.

I think that, overall, writing the plugin API with wrappers is flawed, but is still a better option than integrating it directly into the game. The best that can be done is to improve how the API is written in other areas. It would also be nice if the XML docs were released.

**Comment by Jesus-QC** [comment]
Really true. Collaboration would die.
