### ISSUE TITLE
Cancelling PlayerHandcuff event doesn't prevent player to be cuffed

### ISSUE THREAD

**Issue by Lufou** [northwood-studios/NwPluginAPI#148]
Returning false on the event PlayerHandcuff doesn't prevent the targeted player from being cuffed.
The following picture shows that the player is cuffed whatever the result of the ExecuteEvent returned value.

![Proof](https://user-images.githubusercontent.com/21986877/211541810-c7336f67-ed40-4079-81ac-47188528e784.png)

**Comment by zabszk** [comment]
The bug has been fixed in the base game and will be included in the next release.
