### ISSUE TITLE
Add Intercom speaking events

### ISSUE THREAD

**Issue by Lufou** [northwood-studios/NwPluginAPI#149]
Like PlayerStartUsingIntercom ; PlayerStopUsingIntercom or simply PlayerUsingIntercom

**Comment by SrLicht** [comment]
Ok

**Comment by Lufou** [comment]
Thanks, I would put the ExecuteEvent in the `Intercom.Update()` method, in the `IntercomState.Ready` state so that if we cancel the event, IntercomState stay on Ready
