### ISSUE TITLE
[Bug] Config folder with port 0

### ISSUE THREAD

**Issue by SrLicht** [northwood-studios/NwPluginAPI#150]
No matter how many times I do this this folder is not deleted, it happens since 11.0

![image](https://user-images.githubusercontent.com/36207738/211636063-9713e301-5862-4b3e-988c-08a37fcc1c96.png)

**Comment by SrLicht** [comment]
wrong repository 💀

**Comment by moddedmcplayer** [comment]
Uncertain if bug :troll
