### ISSUE TITLE
Server.Instance.GameObject doesn't exist after a round restart, because it's set only once.

### ISSUE THREAD

**Issue by Xname7** [northwood-studios/NwPluginAPI#153]

**Comment by Lufou** [comment]
True, Server.Instance is only set in `Server.Init()`

**Comment by SrLicht** [comment]
Maybe I shouldn't do this, but since Zabs is currently working on a new release, ping @zabszk

**Comment by SrLicht** [comment]
Don't kill me zabs

**Comment by zabszk** [comment]
> Maybe I shouldn't do this, but since Zabs is currently working on a new release, ping @zabszk 

Yeah, I'm working on the new release. Would it be possible for you guys to make a quick PR?
