### ISSUE TITLE
Cancelling PlayerInteractDoor event breaks keycard denied bleep

### ISSUE THREAD

**Issue by ThijsNameIsTaken** [northwood-studios/NwPluginAPI#156]
Refer to the video below.
https://user-images.githubusercontent.com/19609431/212556780-cfb6444c-bb39-4f74-9719-b9ff2682fcd5.mp4

**Comment by zabszk** [comment]
It's an intented behavior.

Cancelling PlayerInteractDoor doesn't mean that the access is denied. Let's say you want to make a plugin that delays opening of the door by 5 seconds. In that case you want to display access granted (with an extra message, eg. using Broadcast system), not access denied text.

Cancelling the event doesn't mean that the access is denied. It means that the game should not process the event further and your plugin handles it from now on.
