### ISSUE TITLE
ServerEventType.PlayerDamage should pass damage and hitbox as a parameter

### ISSUE THREAD

**Issue by SwiftKraft** [northwood-studios/NwPluginAPI#175]
It might just be me not knowing how to use the API, but I cannot find a way to access the damage and hitbox for `PlayerDamage` events.

**Comment by paralyzable** [comment]
if you just want hitbox and damage you can cast to StandardDamageHandler
```
[PluginEvent(ServerEventType.PlayerDamage)]
void OnPlayerDamage(Player victim, Player attacker, DamageHandlerBase damage)
{
   if(damage is StandardDamageHandler standard)
    {
        standard.Hitbox...
        standard.Damage...
    }
}
```
there are many other damaged handlers if you need more information/restrictions

**Comment by SwiftKraft** [comment]
Ah, thx
