### ISSUE TITLE
How to track players

### ISSUE THREAD

**Issue by paralyzable** [northwood-studios/NwPluginAPI#176]
I would like to track users across games with a database what should I use for a pk. How about steamid64? Is there anyway to get it?

**Comment by paralyzable** [comment]
ok found it, 
```
player.ReferenceHub.characterClassManager.UserId
```

**Comment by SrLicht** [comment]
Player.UserId

**Comment by SrLicht** [comment]
https://github.com/northwood-studios/NwPluginAPI/blob/master/NwPluginAPI/Core/Player.cs
