### ISSUE TITLE
ICommand type is not found

### ISSUE THREAD

**Issue by SwiftKraft** [northwood-studios/NwPluginAPI#177]
How do you create a command? I tried using the plugin template but it just has a bunch of types that was not found

**Comment by SrLicht** [comment]
You need ``Assembly-CSharp.dll`` since the Icommand interface is in the game (in the class put ``using CommandSystem;``).

https://github.com/northwood-studios/NwPluginAPI/blob/master/TemplatePlugin/Commands/TestCommand.cs

**Comment by SwiftKraft** [comment]
> You need `Assembly-CSharp.dll` since the Icommand interface is in the game (in the class put `using CommandSystem;`).
> 
> https://github.com/northwood-studios/NwPluginAPI/blob/master/TemplatePlugin/Commands/TestCommand.cs

I did put `using CommandSystem;`
in fact I copied and pasted the template. It cannot find `CommandHandler` and `ICommandSender` as well

**Comment by moddedmcplayer** [comment]
> > You need `Assembly-CSharp.dll` since the Icommand interface is in the game (in the class put `using CommandSystem;`).
> > 
> > https://github.com/northwood-studios/NwPluginAPI/blob/master/TemplatePlugin/Commands/TestCommand.cs
> 
> I did put `using CommandSystem;`
> in fact I copied and pasted the template. It cannot find `CommandHandler` and `ICommandSender` as well

GameConsoleCommandHandler
ClientCommandHandler
RemoteAdminCommandHandler
all inside Assembly-CSharp
Feel free to ask me in discord :)
