### ISSUE TITLE
Sometimes, server won't heartbeat.

### ISSUE THREAD

**Issue by Kamisato-Ayaka-233** [northwood-studios/NwPluginAPI#179]
As the title, that's a serious problem, it will cause server restarting. i dont know why.

umm, my plugin is a little large.

**Comment by moddedmcplayer** [comment]
plugin issue? Lmfao

**Comment by Kamisato-Ayaka-233** [comment]
umm, it seem isn't my plugin's problem.

this problem is triggered irregularly. it seem that every a few or dozens of rounds, the server will not heartbeat, causing my server to restart.

**Comment by moddedmcplayer** [comment]
Happens without plugins and on diff machines?

**Comment by moddedmcplayer** [comment]
I have a small suspicion it might be your plugin causing the server to freeze for a few seconds due to allocating all it's resources on your plugin.

**Comment by Kamisato-Ayaka-233** [comment]
> Happens without plugins and on diff machines?

with plugins, it's on my server.

And I found that, if there are a lot of players on the server, this problem will happen more frequently.

---

> I have a small suspicion it might be your plugin causing the server to freeze for a few seconds due to allocating all it's resources on your plugin.

umm, my plugin is a little large, is this caused?

or, how can i improve it?

**Comment by moddedmcplayer** [comment]
If it dosent happen without plugins it's not a nwapi issue but a skill issue, on your side.
You should add some logging to see what might be causing it.
Unless you can replicate this without plugins, I recommend you close the issue and ask for support the discord, however we can't really do that much unless you're willing to share the source code.

**Comment by Kamisato-Ayaka-233** [comment]
ok, i will check it.
