### ISSUE TITLE
Add event for offline bans

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#180]

**Comment by SrLicht** [comment]
The BanIssued event fulfills that function.
https://github.com/northwood-studios/NwPluginAPI/blob/master/NwPluginAPI/Enums/ServerEventType.cs#L856

![image](https://user-images.githubusercontent.com/36207738/220199275-bb5456b5-dd0d-4c08-a6f6-2a2f1cadb68d.png)
![image](https://user-images.githubusercontent.com/36207738/220199329-608e4e22-4bf3-4b45-932c-571c0efea7b8.png)

**Comment by KarlOfDuty** [comment]
Great, thanks!

**Comment by KarlOfDuty** [comment]
It doesn't seem like the BanIssued event has any information about it being an online or offline ban, so I think wither that should be added or a seperate event matching PlayerBanned for only offline bans should be added. Otherwise I would have it trigger twice for all online bans as I still need the player information in PlayerBanned for that event.

**Comment by moddedmcplayer** [comment]
How about you see if there is someone online with that id instead

**Comment by KarlOfDuty** [comment]
Usually when someone is banned they are no longer online.
