### ISSUE TITLE
[BETA] PlayerBannedEvent use IPlayer instead of Player

### ISSUE THREAD

**Issue by SrLicht** [northwood-studios/NwPluginAPI#203]
https://github.com/northwood-studios/NwPluginAPI/blob/aab64bb041a928f50009865f219a577a6edd19b5/NwPluginAPI/Events/Args/Player/PlayerBannedEvent.cs#L13
https://github.com/northwood-studios/NwPluginAPI/blob/aab64bb041a928f50009865f219a577a6edd19b5/NwPluginAPI/Events/Args/Player/PlayerBannedEvent.cs#L15

**Comment by moddedmcplayer** [comment]
pr it

**Comment by SrLicht** [comment]
im lazy

**Comment by moddedmcplayer** [comment]
It’s 1 character

**Comment by ced777ric** [comment]
IPlayer exists as Parameter there because the banned player can also be an OfflinePlayer
