### ISSUE TITLE
Some hotkeys are not being fired on hotkeypressed event

### ISSUE THREAD

**Issue by REALMWTH** [northwood-studios/NwPluginAPI#25]
The most important for me that don't fire:

VoiceChat
AltVoiceChat
RemoteAdmin
PlayerList
CharacterInfo
GameConsole
HideGUI
NoClipFogToggle
DebugLogMenu
PauseMenu

**Comment by zabszk** [comment]
These hotkeys are handled client-side and are not synced to the server.
