### ISSUE TITLE
Suggestion: new events

### ISSUE THREAD

**Issue by REALMWTH** [northwood-studios/NwPluginAPI#26]
Updated requested events list:

```
SCP079Interaction
SCP914ChangeKnob
SCP914Activate
PlayerInteractDoor
RoundSpawnRoles (so we can alter player roles on round start automatically)
ReinforcementArrive
ReinforcementPrepare
```

**Comment by zabszk** [comment]
Partially resolved by #34.

**Comment by zabszk** [comment]
Updated list of requested events (already added events have been removed):
```
SCP079Interaction
SCP914ChangeKnob
SCP914Activate
PlayerInteractDoor
RoundSpawnRoles (so we can alter player roles on round start automatically)
ReinforcementArrive
ReinforcementPrepare
```

**Comment by KarlOfDuty** [comment]
- [ ] SCP079Interaction
- [ ] SCP914ChangeKnob
- [ ] SCP914Activate
- [ ] PlayerInteractDoor
- [ ] RoundSpawnRoles (so we can alter player roles on round start automatically)
- [ ] ReinforcementArrive
- [ ] ReinforcementPrepare

**Comment by REALMWTH** [comment]
A new event needed:
```
PlayerPreauthBanCheck (so we can alter ban reason if it's located in, for example, MySQL database)
```

**Comment by zabszk** [comment]
> A new event needed:
> 
> ```
> PlayerPreauthBanCheck (so we can return ban reason and duration if it's located in, for example, MySQL database)
> ```

I'm not sure such event is needed. I haven't seen any other modding framework having such event. Custom ban systems usually use regular preauth event and override ban commands, so bans are not stored locally.

In this case you want a system that stores bans both locally and in the database, but the local bans are saved with invalid duration or ban reason, so you need to overwrite them with the DB data? I don't really see any other use of such event.

**Comment by REALMWTH** [comment]
> > A new event needed:
> > ```
> > PlayerPreauthBanCheck (so we can return ban reason and duration if it's located in, for example, MySQL database)
> > ```
> 
> I'm not sure such event is needed. I haven't seen any other modding framework having such event. Custom ban systems usually use regular preauth event and override ban commands, so bans are not stored locally.
> 
> In this case you want a system that stores bans both locally and in the database, but the local bans are saved with invalid duration or ban reason, so you need to overwrite them with the DB data? I don't really see any other use of such event.

We have custom web interface that allows staff members to alter ban details stored in DB. Right now we patch ban handler to request data from DB via httprequest. But yes, I've forgot about preauth event 🤦 

It is easy to override answer, thanks ;)

**Comment by REALMWTH** [comment]
Missing
```
RoundSpawnRoles (so we can alter player roles on round start automatically)```
