### ISSUE TITLE
Can't register events in a separate event handler

### ISSUE THREAD

**Issue by Liassid** [northwood-studios/NwPluginAPI#28]
Registering events is only currently possible if handlers are in the same place as plugin entry point. It's not possible to register events in separate handlers.

![image](https://user-images.githubusercontent.com/53168424/200119680-6f972d3e-7415-417d-bf26-024a8cf7f3cb.png)
![image](https://user-images.githubusercontent.com/53168424/200119692-be3921f3-63c7-44c7-8b9b-80378eda54e8.png)
![image](https://user-images.githubusercontent.com/53168424/200119707-d7985d59-f960-491a-a662-4454719afb8f.png)

**Comment by Killers0992** [comment]
Just use properly generic methods and answer its just
```C#
EventManager.RegisterEvents<Base>(this);
```

**Comment by sirmeepington** [comment]
generics are hard 👍

**Comment by Liassid** [comment]
> Just use properly generic methods and answer its just
> 
> ```cs
> EventManager.RegisterEvents<Base>(this);
> ```

That was obviously the first thing I tried
![image](https://user-images.githubusercontent.com/53168424/200132988-0d520481-6501-4113-9f12-5ed617c809fa.png)
![image](https://user-images.githubusercontent.com/53168424/200133000-681b57ac-20cb-47ff-9e5a-98fc83f36012.png)

**Comment by sirmeepington** [comment]
Looks to actually be a bug then and killers doesn't know how generics work. See #29
