### ISSUE TITLE
Server.RunCommand should take a sender parameter type included in the API so it doesn't depend on Assembly-CSharp.dll

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#32]
As Server inherits from the Player class this should be fine.

**Comment by zabszk** [comment]
There are other types of CommandSenders than only a Player and you can define a custom one to receive output somewhere else or specify custom permissions of the sender.

**Comment by KarlOfDuty** [comment]
Ah I see, maybe the class should just be included in the API then?

**Comment by KarlOfDuty** [comment]
As the entire api depends on assembly-csharp this doesnt seem useful.
