### ISSUE TITLE
Player Damaged event should provide a StandardDamageHandler instead of a DamageHandlerBase

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#41]
This makes it easier to get the damage value and all damage types inherit from StandardDamageHandler anyway so there is no need to be more generic.

**Comment by zabszk** [comment]
`PlayerStats.DealDamage` takes `DamageHandlerBase`, so `DamageHandlerBase` by the API.

Keep in mind that in the future there might be a damage handler that isn't StandardDamageHandler and that would require changing entire API. Plugins may create own damage handlers as well, so even some plugin may create a custom one based on DamageHandlerBase and pass it as an argument to DealDamage.
