### ISSUE TITLE
RoundEnd event should have info on how the round ended

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#58]
I would like these things for scpdiscord, and an enum saying who won would also be nice.

![image](https://user-images.githubusercontent.com/18099825/205494772-86edace8-6d8a-47a3-bc8b-02ffa128ead5.png)

**Comment by Killers0992** [comment]
```
Statistics.CurrentRound
```
https://github.com/northwood-studios/NwPluginAPI/blob/9db1d1d28aeb74dedf5ec0212eeeac283ab65e13/NwPluginAPI/Core/Statistics.cs#L79
