### ISSUE TITLE
Add setrank function to the player class

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#60]
Basically this but with the group part fixed. You could simply make the permissions handler public in the game and use this exact code.

![image](https://user-images.githubusercontent.com/18099825/205515512-c5a8c0e8-2150-4229-86b4-3fb3c9ca5c4d.png)

```cs
public static void SetRank(this Player player, string color = null, string text = null, string group = null)
{
	ServerRoles roleComponent = player.ReferenceHub.serverRoles;

	if (roleComponent != null)
	{
		// TODO: Fix vanilla ranks
		if (group != null)
			roleComponent.SetGroup(ServerStatic.PermissionsHandler.GetGroup(group), false);
		if (color != null)
			roleComponent.SetColor(color);
		if (text != null)
			roleComponent.SetText(text);
	}
}
```

**Comment by moddedmcplayer** [comment]
pr it

**Comment by KarlOfDuty** [comment]
Add me to the org and I will.

**Comment by moddedmcplayer** [comment]
fork it and open pr

**Comment by KarlOfDuty** [comment]
I am unable to do so as I do not have access.

**Comment by moddedmcplayer** [comment]
![image](https://user-images.githubusercontent.com/76910334/205851085-d28e1120-7212-42f6-8ef0-afa9894232d7.png)
![image](https://user-images.githubusercontent.com/76910334/205851148-90b8a17e-eea6-4be4-8357-b12d651f8cbc.png)

**Comment by KarlOfDuty** [comment]
> I am unable to do so as I do not have access.

**Comment by KarlOfDuty** [comment]
Thats in this repo, we are talking about the game repo.

**Comment by zhaguanyang** [comment]
Use publicized assembly?

**Comment by KarlOfDuty** [comment]
How would that help? That would just allow me personally to get around it?

**Comment by zhaguanyang** [comment]
There are many functions that will be requiring a publicized assembly, you can't expect NW to make all of them public.

**Comment by KarlOfDuty** [comment]
I don't really understand what you mean, how does this help anything? If I push something that requires a modded assembly-cs that would just mean no one else can build it?

And yes I very much expect it for their own modding API, it is literally a part of the game.

**Comment by zhaguanyang** [comment]
Basically, everyone should be using a modded assembly if they want to build it. I don't see that's a huge issue. I tried to implement a Player.Kill feature #56,  yet that simple feature uses a method that is not public. And that's not just you and I problem, it goes for everyone. As this API is growing, it's expected to see many features needed will be using non-public methods/properties. There's absolutely no way all of them become public.

**Comment by KarlOfDuty** [comment]
What the actual hell, how is this the policy? Especially for an official api.

**Comment by zhaguanyang** [comment]
That's not a policy, just my personal idea. But I don't see how this will not be a thing, unless you have a better solution.

**Comment by KarlOfDuty** [comment]
Well that they implement their own API is something I feel might be reasonable.

**Comment by zabszk** [comment]
There is `GetPermissionsHandler()` method in `ServerStatic`.
