### ISSUE TITLE
Paths.Config and Paths.Global don't seem to ever be set

### ISSUE THREAD

**Issue by KarlOfDuty** [northwood-studios/NwPluginAPI#62]
Noticed they weren't set when I tried to use them and it doesn't seem like there is even any code to do it unless it is elsewhere.

![image](https://user-images.githubusercontent.com/18099825/206576684-020e7ea0-5fee-4ce0-8d59-dc74bb112564.png)

**Comment by zabszk** [comment]
`Paths.Config` has been fixed, `Paths.Global` isn't fixed yet.
