### ISSUE TITLE
Add PlayerBanning and PlayerKicking Events and a way to prevent them

### ISSUE THREAD

**Issue by Neil925** [northwood-studios/NwPluginAPI#79]
Currently, there are events to handle players that have already been banned or kicked. But for the purposes of certain plugins, particularly ones that use an online web panel and API, there needs to be a way to run logic _before_ a ban or kick and a way to prevent it. Currently, the only solution is to unban someone immediately after they get banned, which is inconvenient.

**Comment by zabszk** [comment]
There are `PlayerBanned` and `PlayerKicked` events and both are cancellable.

There isn't an event for offline bans (`oban` command), but that event may be added.

**Comment by zabszk** [comment]
One more related event (`BanUpdated`) is added by #87.
