### ISSUE TITLE
Event 99 is not registered in manager

### ISSUE THREAD

**Issue by PlayboyPrime** [northwood-studios/NwPluginAPI#91]
![image](https://user-images.githubusercontent.com/55946112/208270550-c4f91975-8b8a-453a-b86a-ec43eb3f706c.png)
![image](https://user-images.githubusercontent.com/55946112/208270551-df373e44-849b-4517-a9ed-e577e8ac6063.png)

**Comment by moddedmcplayer** [comment]
update pluginapi on server

**Comment by zabszk** [comment]
You are using a newer API version that is on your server.

You need to either update your server to the latest API beta (`pluginapi-beta`) or develop plugins using the same version of PluginAPI that the one your server use. You can download all versions of PluginAPI from nuget and release section of this repository.
