### ISSUE TITLE
Assembly-Csharp bug: operator of RecyclablePlayerId 

### ISSUE THREAD

**Issue by warquys** [northwood-studios/NwPluginAPI#94]
The is issue is from [discord](https://discord.com/channels/974269642480685056/1053979057076834384);

RecyclablePlayerId overloading equality operations but don't check if left side is null.
current code:
```cs
    public static bool operator ==(RecyclablePlayerId left, RecyclablePlayerId right) => left.Equals(right);

    public static bool operator !=(RecyclablePlayerId left, RecyclablePlayerId right) => !left.Equals(right);
```
Either there is an error on the fact that RecyclablePlayerId must be a structure and not a class or there was an error when defining the `==`.
Maby do this :
```cs
   public static bool operator ==(RecyclablePlayerId left, RecyclablePlayerId right)
    {
        if (left is null)
        {
            if (right is null)
            {
               return true;
            }
            return false;
        }
        return left.Equals(right);
    }

    public static bool operator !=(RecyclablePlayerId left, RecyclablePlayerId right) => !(left == right);
```
or change it to `struct`. 

based on this [doc](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type).

**Comment by moddedmcplayer** [comment]
```
  public static bool operator ==(RecyclablePlayerId left, RecyclablePlayerId right) => left?.Equals(right) ?? right == null ? true : false;
  
  public static bool operator !=(RecyclablePlayerId left, RecyclablePlayerId right) => !left?.Equals(right) ?? right == null ? true :false;
```

**Comment by warquys** [comment]
if you whant to do it like this do it right
  ```cs
  public static bool operator ==(RecyclablePlayerId left, RecyclablePlayerId right) => left?.Equals(right) ?? right is null ? true : false;
  
  public static bool operator !=(RecyclablePlayerId left, RecyclablePlayerId right) => !(left == right);
  ```
  bc you `!=` don't check correct if the other side `is null` and if you use `==` you do a loop. Also that is cryptic and not scalable.

**Comment by moddedmcplayer** [comment]
left?.Equals(right) ?? right is null ? true : false; 
how is that a loop

**Comment by zabszk** [comment]
I have reported this bug to our programming team, because it's not an NW API bug. This will be changed into a struct.

**Comment by zabszk** [comment]
It has been changed to a struct on the master game branch. Expect a release soon.
