### ISSUE TITLE
PlayerRemoteAdminCommand event should have CommandSender as first argument

### ISSUE THREAD

**Issue by REALMWTH** [northwood-studios/NwPluginAPI#97]
We can't cast Player to CommandSender, that's why I can't use RaReply method if I want to cancel command execution and return the reason to player.

**Comment by REALMWTH** [comment]
Update: it seems to impossible to return correct response using this event. Please enhance it, so we can override response.

**Comment by zabszk** [comment]
For now you can use `new PlayerCommandSender(player.queryProcessor)` to get the sender.

I agree that PlayerRemoteAdminCommand, PlayerRemoteAdminCommandExecuted, ConsoleCommand and ConsoleCommandExecuted should have CommandSender as a first argument.
